// This file contains TypeScript types for your Supabase database
// Generated by Supabase CLI
// You can generate this file by running: npx supabase gen types typescript --project-id YOUR_PROJECT_ID

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      files: {
        Row: {
          id: string
          user_id: string
          name: string
          key: string
          url: string | null
          size: number
          type: string
          status: string
          created_at: string
          updated_at: string
          expires_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          key: string
          url?: string | null
          size: number
          type: string
          status?: string
          created_at?: string
          updated_at?: string
          expires_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          key?: string
          url?: string | null
          size?: number
          type?: string
          status?: string
          created_at?: string
          updated_at?: string
          expires_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "files_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      api_keys: {
        Row: {
          id: string
          user_id: string
          name: string
          key: string
          permissions: string[]
          is_active: boolean
          created_at: string
          updated_at: string
          expires_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          key: string
          permissions?: string[]
          is_active?: boolean
          created_at?: string
          updated_at?: string
          expires_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          key?: string
          permissions?: string[]
          is_active?: boolean
          created_at?: string
          updated_at?: string
          expires_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "api_keys_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      usage_records: {
        Row: {
          id: string
          user_id: string
          api_key_id: string | null
          service: string
          operation: string
          resource_id: string | null
          units: number
          cost: number
          status_code: number | null
          timestamp: string
        }
        Insert: {
          id?: string
          user_id: string
          api_key_id?: string | null
          service: string
          operation: string
          resource_id?: string | null
          units?: number
          cost?: number
          status_code?: number | null
          timestamp?: string
        }
        Update: {
          id?: string
          user_id?: string
          api_key_id?: string | null
          service?: string
          operation?: string
          resource_id?: string | null
          units?: number
          cost?: number
          status_code?: number | null
          timestamp?: string
        }
        Relationships: [
          {
            foreignKeyName: "usage_records_user_id_fkey"
            columns: ["user_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "usage_records_api_key_id_fkey"
            columns: ["api_key_id"]
            referencedRelation: "api_keys"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {}
    Functions: {}
    Enums: {}
  }
}
